### ISSUE TITLE
edgengram not working with elastocstack

### ISSUE THREAD

**Issue by jamartinh** [bennylope/elasticstack#10]
Hello, I am trying to add an edgengram field, but when I use elasticstack the autocomplete field gets created as a string type.

What can I touch ?

Thanks !

**Comment by bennylope** [comment]
I'm going to summarize to see if I understand:

You're using an EdgeNgram field by using the BaseEdgeNgram field from elasticstack, and this field is created as a CharField instead (e.g. a `string` for ElasticSearch).

Is this what is returned by the management command [`show_mapping`](https://github.com/bennylope/elasticstack#show_mapping)? What if you use the `--detail` flag, what do you see in the `analyzer` key? I think it's okay if it's a string, as long as its using the right analyzer...

**Comment by jamartinh** [comment]
Hi Ben, thanks, I will ser it  tomorrow .

However, what I see is that if I switch to not using elasticstack then the
field is created as Edgengram another estructure is created in the index. I
will send more details tomorrow.

Thanks again for the reply.
Cheers,
Jose

**Comment by jamartinh** [comment]
Hello Ben, this is what I get with --detail
It is good ?

"aautocomplete": {
        "type": "string",
        "analyzer": "edgengram_analyzer"

Also, when using elasticstack, should I use always the new fields defined in elastistack or can I mix from haystack indexes and elasticstack search fields ?

Thanks a lot for our help.

**Comment by bennylope** [comment]
It *looks* fine to me. It's a string value, but what matters is the analyzer.

As for mixing fields classes from Haystack and from elasticsatck, it's totally fine.

**Comment by jamartinh** [comment]
Thanks a lot!



2015-02-02 20:30 GMT+01:00 Ben Lopatin <notifications@github.com>:

> It *looks* fine to me. It's a string value, but what matters is the
> analyzer.
>
> As for mixing fields classes from Haystack and from elasticsatck, it's
> totally fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bennylope/elasticstack/issues/10#issuecomment-72520963>
> .
>



-- 
/ .- .-.. .-.. / -.-- --- ..- / -. . . -.. / .. ... / .-.. --- ...- .
José Antonio Martín H. (PhD)           E-Mail: jamartinh@fdi.ucm.es
Computer Science Faculty               Phone: (+34) 91 3947650
Complutense University of Madrid       Fax: (+34) 91 3947527
C/ Prof. José García Santesmases,s/n   28040 Madrid, Spain
web: http://www.dacya.ucm.es/jam/
LinkedIn: http://www.linkedin.com/in/jamartinh (Let's connect)
.-.. --- ...- . / .. ... / .- .-.. .-.. / .-- . / -. . . -..
