### ISSUE TITLE
Support for fuzzy queries?

### ISSUE THREAD

**Issue by discopatrick** [bennylope/elasticstack#14]
Is it possible to run a fuzzy query with elasticstack? Or even with haystack itself?

https://www.elastic.co/guide/en/elasticsearch/guide/current/fuzzy-query.html#fuzzy-query

**Comment by bennylope** [comment]
Sorry for leaving this for so long. Elasticstack isn't going to give you any special help here. It might be something where you need to make more use of raw search queries though.
