### ISSUE TITLE
Add support for "no" option of "index" attribute

### ISSUE THREAD

**Issue by barseghyanartur** [bennylope/elasticstack#16]
It would be great to have support "no" option of "index" attribute. See the docs:

- https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html#_index_2

**Comment by bennylope** [comment]
What's the benefit of doing this, as opposed to marking search fields with [`indexed = False`](http://django-haystack.readthedocs.org/en/v2.4.1/searchfield_api.html#indexed)?

**Comment by barseghyanartur** [comment]
That's not the same.

**Comment by bennylope** [comment]
How do they differ, in effect, at least?

**Comment by barseghyanartur** [comment]
@bennylope:

In the docs of Haystack:

- https://django-haystack.readthedocs.org/en/latest/searchindex_api.html#stored-indexed-fields

> By default, all fields in Haystack are both indexed (searchable by the engine) and stored (retained by the engine and presented in the results). By using a stored field, you can store commonly used data in such a way that you don’t need to hit the database when processing the search result to get more information.

In the ElasticSearch backend if field is set to indexed=False it is being set to "not_analyzed", which is fine. In terms of ElasticSearch index="no" means that the field is present in the index, but is not searchable.

Quote from ElasticSearch:

- https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html#_index_2

> The index attribute controls how the string will be indexed. It can contain one of three values:
> 
> - analyzed: First analyze the string and then index it. In other words, index this field as full text.
> - not_analyzed: Index this field, so it is searchable, but index the value exactly as specified. Do not analyze it.
> - no: Don’t index this field at all. This field will not be searchable.
