### ISSUE TITLE
Installing on python 3.5 on latest ubuntu 16.04

### ISSUE THREAD

**Issue by Visgean** [bennylope/elasticstack#22]
When I try to install latest version ``0.4.0`` I get following error:

```
Collecting elasticstack==0.4.0 (from -r requirements.txt (line 31))
  Downloading elasticstack-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w06rudbl/elasticstack/setup.py", line 10, in <module>
        readme = open('README.rst').read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6280: ordinal not in range(128)
```

**Comment by bennylope** [comment]
Anything else you can tell me about this? Have you tried on multiple Ubuntu 16.04 systems or just one?

I just spun up an Ubuntu 16.04 VM and installed successfully using Python 3.5.1, so trying to figure out what might differ. Locale, I'd presume, but I don't know why that would affect this operation.

**Comment by Visgean** [comment]
I am using official docker image for ubuntu: https://github.com/WebArchivCZ/Seeder/blob/master/Dockerfile that might differ somehow from the VM...

**Comment by Visgean** [comment]
hi, thanks for the fix, you bumped the version in setup but you did not push it to pypi :/

**Comment by bennylope** [comment]
It's on PyPI now if you want to try it out.

>  but you did not push it to pypi :/

No guarantees implied! That was intentional at any rate, I didn't want to push a new version just prior to going to bed.
