### ISSUE TITLE
Slower results after ELASTICSEARCH_DEFAULT_ANALYZER

### ISSUE THREAD

**Issue by sandeepsayone** [bennylope/elasticstack#24]
I am experiencing slower results  after setting 
ELASTICSEARCH_DEFAULT_ANALYZER = 'simple'

Is it possible that changing the analyzer could slow down the search ? My OS is ubuntu 12.04, django version used is 1.7. elasticstack==0.4.0

**Comment by bennylope** [comment]
I suppose it is possible, although I'd probably track whether the index was updated using this first and then see what the logs tell you.

**Comment by sandeepsayone** [comment]
Index was updated. Where do i look for the logs ? Would the issue be fixed if django is upgraded and new elasticstack is used ?
